btn_form = "//android.view.View[@content-desc, 'Forms']"
input_field = "//android.widget.EditText[@content-desc='text-input']"
input_result = "//android.widget.TextView[@content-desc='input-text-result']"
swithc_toggle = "//android.widget.Switch[@content-desc='switch']"
dropdown = "//android.view.ViewGroup[@content-desc='Dropdown']/android.view.ViewGroup/android.widget.EditText"
text_drpdwn1 = "//*/android.widget.CheckedTextView[2]"
text_drpdwn2 = "//*/android.widget.CheckedTextView[3]"
text_drpdwn3 = "//*/android.widget.CheckedTextView[4]"
btn_active = "//android.view.ViewGroup[@content-desc='button-Active']/android.view.ViewGroup"
btn_inactive = "//android.view.ViewGroup[@content-desc='button-Inactive']/android.view.ViewGroup"
